version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/server/main.go
    env_file: .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog_api
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
