// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generatedmodel

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type AlbumFilter struct {
	// Find Albums by name.
	Name      *string    `json:"name"`
	AlbumType *AlbumType `json:"albumType"`
}

type AlbumInput struct {
	ID   *int   `json:"id"`
	Name string `json:"name"`
	// Release time and date of the album. ISO 8601 format required.
	ReleasedAt time.Time `json:"releasedAt"`
	AlbumType  AlbumType `json:"albumType"`
	// IDs for existing Tracks that this Album has.
	TrackIds []int `json:"trackIds"`
}

type ArtistFilter struct {
	// Find Artists by name.
	Name *string `json:"name"`
}

type ArtistInput struct {
	ID   *int   `json:"id"`
	Name string `json:"name"`
}

type GenreInput struct {
	ID   *int   `json:"id"`
	Name string `json:"name"`
}

// Filters used for narrowing down a Track list.
type TrackFilter struct {
	// Find Tracks by name.
	Name *string `json:"name"`
	// Find Track s by a related Artist's ID.
	ArtistID *int `json:"artistId"`
	// Find Tracks by a related Artist's Name.
	ArtistName *string `json:"artistName"`
}

type TrackInput struct {
	ID   *int   `json:"id"`
	Name string `json:"name"`
	// Track duration in milliseconds.
	DurationMs int `json:"durationMS"`
	// IDs for existing Artists that this Track belongs to.
	ArtistIds []int `json:"artistIds"`
	// IDs for existing Albums that this Track belongs to.
	AlbumIds []int `json:"albumIds"`
	// IDs for existing Genres that this Track has.
	GenreIds []int `json:"genreIds"`
}

type AlbumType string

const (
	AlbumTypeAlbum       AlbumType = "ALBUM"
	AlbumTypeSingle      AlbumType = "SINGLE"
	AlbumTypeCompilation AlbumType = "COMPILATION"
)

var AllAlbumType = []AlbumType{
	AlbumTypeAlbum,
	AlbumTypeSingle,
	AlbumTypeCompilation,
}

func (e AlbumType) IsValid() bool {
	switch e {
	case AlbumTypeAlbum, AlbumTypeSingle, AlbumTypeCompilation:
		return true
	}
	return false
}

func (e AlbumType) String() string {
	return string(e)
}

func (e *AlbumType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlbumType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlbumType", str)
	}
	return nil
}

func (e AlbumType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
