// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Albums       string
	Artists      string
	Genres       string
	TrackAlbums  string
	TrackArtists string
	TrackGenres  string
	Tracks       string
}{
	Albums:       "albums",
	Artists:      "artists",
	Genres:       "genres",
	TrackAlbums:  "track_albums",
	TrackArtists: "track_artists",
	TrackGenres:  "track_genres",
	Tracks:       "tracks",
}
